# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

## _config.yml
title: Smart Punctuation Converter
description: Convert straight quotes to elegant curved quotation marks
url: "https://YOUR_USERNAME.github.io"
baseurl: "/smart-punctuation"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SCSS Configuration for assets/css/style.scss
sass:
  style: compressed  # Remove sass_dir since we're using assets/css/

# Exclude files from processing
exclude:
  - vendor/
  - node_modules/
  - package.json
  - package-lock.json
  - server.js
  - public/
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Site settings
author: Ramasas
github_username: ramasas

# Custom variables
app:
  name: "Smart Punctuation Converter"
  version: "1.0.0"
  description: "Inspired by Calibre's Smarten Punctuation feature"

# Collections (if you want to add blog posts or docs later)
collections:
  docs:
    output: true
    permalink: /:collection/:name/